// Mobile Data-----------------------------------------------------------------

const accessories = [
    {
        id:1,
        img:'https://rukminim2.flixcart.com/image/832/832/xif0q/mobile/u/n/p/-original-imagugptgsfbxauz.jpeg?q=70',
        imgCousins:[
            'https://rukminim2.flixcart.com/image/832/832/xif0q/mobile/p/u/8/-original-imagugptptuacajg.jpeg?q=70',
            'https://rukminim2.flixcart.com/image/832/832/xif0q/mobile/t/c/p/-original-imagugptdmkvpwpm.jpeg?q=70',
            'https://rukminim2.flixcart.com/image/832/832/xif0q/mobile/f/r/2/-original-imagugptvr3dbzpb.jpeg?q=70'
        ],
        model:'vivo Y200 ',
        brand:'Vivo',
        price:21988,
        color:'',
        space:'8 GB RAM | 128 GB ROM',
        camera:'64MP + 2MP | 16MP Front Camera',
        battery:'4800 mAh Battery',
        count:1,
        isAdded:false,
        type:'Mobile',   
        isTrending:true
    },
    {
        id:2,
        img:'https://rukminim2.flixcart.com/image/832/832/xif0q/mobile/w/x/0/-original-imagszg3qxqgdx9c.jpeg?q=70',
        imgCousins:[
            'https://rukminim2.flixcart.com/image/832/832/xif0q/mobile/k/d/m/-original-imagszg3zmt5ungh.jpeg?q=70',
            'https://rukminim2.flixcart.com/image/832/832/xif0q/mobile/x/l/v/-original-imagszg34azybw4z.jpeg?q=70',
            'https://rukminim2.flixcart.com/image/832/832/xif0q/mobile/u/s/4/-original-imagszg3nhwkfaah.jpeg?q=70'
        ],
        model:'Infinix Zero 30 ',
        brand:'Infinix',
        price:23999,
        space:'12 GB RAM | 256 GB ROM',
        camera:'108MP + 13MP + 2MP | 50MP Front Camera',
        battery:'5000 mAh Battery',
        count:1,
        isAdded:false,
        type:'Mobile',   
        isTrending:false

    },
    {
        id:3,
        img:'https://rukminim2.flixcart.com/image/832/832/xif0q/mobile/t/s/y/narzo-60-5g-rmx3750-realme-original-imagrht2yzyc2jyj.jpeg?q=70',
        imgCousins:[
            'https://rukminim2.flixcart.com/image/832/832/xif0q/mobile/h/b/f/narzo-60-5g-rmx3750-realme-original-imagrht2vb5yvpph.jpeg?q=70',
            'https://rukminim2.flixcart.com/image/832/832/xif0q/mobile/h/m/j/narzo-60-5g-rmx3750-realme-original-imagrht23qxhxk4h.jpeg?q=70',
            'https://rukminim2.flixcart.com/image/832/832/xif0q/mobile/e/i/h/narzo-60-5g-rmx3750-realme-original-imagrhsyceebdg9a.jpeg?q=70'
        ],
        model:'realme Narzo 60 ',
        brand:'Realme',
        price:17868,
        space:'8 GB RAM | 128 GB ROM',
        camera:'64MP Rear Camera',
        battery:'5000 mAh Battery',
        count:1,
        isAdded:false,
        type:'Mobile',   
        isTrending:true
    },
    {
        id:4,
        img:'https://rukminim2.flixcart.com/image/832/832/xif0q/mobile/2/z/4/-original-imagqxx2haehpjnf.jpeg?q=70',
        imgCousins:[
            'https://rukminim2.flixcart.com/image/832/832/xif0q/mobile/h/i/y/-original-imagqxx2tzhw9wng.jpeg?q=70',
            'https://rukminim2.flixcart.com/image/832/832/xif0q/mobile/z/r/x/-original-imagqxx26jthuzqp.jpeg?q=70',
            'https://rukminim2.flixcart.com/image/832/832/xif0q/mobile/c/j/w/-original-imagqxx2qwpzmpv6.jpeg?q=70'
        ],
        model:'realme 11 Pro ',
        brand:'Realme',
        price:21999,
        space:'8 GB RAM | 128 GB ROM',
        camera:'100MP (OIS) + 2MP | 16MP Front Camera',
        battery:'5000 mAh Battery',
        count:1,
        isAdded:false,
        type:'Mobile',   
        isTrending:false
    },
    {
        id:5,
        img:'https://rukminim2.flixcart.com/image/832/832/xif0q/mobile/h/h/d/-original-imags487gaqqhcea.jpeg?q=70',
        imgCousins:[
            'https://rukminim2.flixcart.com/image/832/832/xif0q/mobile/w/y/8/-original-imagrsfapauvzsvz.jpeg?q=70',
            'https://rukminim2.flixcart.com/image/832/832/xif0q/mobile/e/k/v/-original-imagrsfabrn83kyf.jpeg?q=70',
            'https://rukminim2.flixcart.com/image/832/832/xif0q/mobile/2/7/f/-original-imagrggwnkdrfdfs.jpeg?q=70'
        ],
        model:'realme C53',
        brand:'Realme',
        price:9999,
        space:'6 GB RAM | 64 GB ROM',
        camera:'108MP + 2MP | 8MP Front Camera',
        battery:'5000 mAh Battery',
        count:1,
        isAdded:false,
        type:'Mobile',   
        isTrending:true
    },
    {
        id:6,
        img:'https://rukminim2.flixcart.com/image/832/832/xif0q/mobile/4/h/e/-original-imagzjhwmsamexfk.jpeg?q=70',
        imgCousins:[
            'https://rukminim2.flixcart.com/image/832/832/xif0q/mobile/f/v/h/-original-imagzjhwkubmddyf.jpeg?q=70',
            'https://rukminim2.flixcart.com/image/832/832/xif0q/mobile/x/l/v/-original-imagszg34azybw4z.jpeg?q=70',
            'https://rukminim2.flixcart.com/image/832/832/xif0q/mobile/u/s/4/-original-imagszg3nhwkfaah.jpeg?q=70'
        ],
        model:'vivo T2x ',
        brand:'Vivo',
        price:12999,
        space:'6 GB RAM | 128 GB ROM',
        camera:'50MP + 2MP | 8MP Front Camera',
        battery:'5000 mAh Battery',
        count:1,
        isAdded:false,
        type:'Mobile',   
        isTrending:false
    },
    {
        id:7,
        img:'https://rukminim2.flixcart.com/image/832/832/xif0q/mobile/l/7/k/-original-imagtxvur9yrxvru.jpeg?q=70',
        imgCousins:[
            'https://rukminim2.flixcart.com/image/832/832/xif0q/mobile/s/k/u/nord-ce-3-lite-5g-ce2099-oneplus-original-imagzj3w2fvgzerg.jpeg?q=70',
            'https://rukminim2.flixcart.com/image/832/832/xif0q/mobile/t/r/r/-original-imagtxvugpakqygr.jpeg?q=70',
            'https://rukminim2.flixcart.com/image/832/832/xif0q/mobile/f/f/b/nord-ce-3-lite-5g-ce2099-oneplus-original-imagzj3wj2wvzsmg.jpeg?q=70'
        ],
        model:'OnePlus Nord',
        brand:'OnePlus',
        price:19420,
        space:'8 GB RAM | 128 GB ROM',
        camera:'108MP Rear Camera',
        battery:'5000 mAh Battery',
        count:1,
        isAdded:false,
        type:'Mobile',   
        isTrending:false
    },
    {
        id:8,
        img:'https://rukminim2.flixcart.com/image/832/832/xif0q/mobile/h/x/a/-original-imagrxbufb6tqzjc.jpeg?q=70',
        imgCousins:[
            'https://rukminim2.flixcart.com/image/832/832/xif0q/mobile/c/q/2/-original-imagrxbuzhbc65gu.jpeg?q=70',
            'https://rukminim2.flixcart.com/image/832/832/xif0q/mobile/s/s/i/a78-5g-cph2495-oppo-original-imagrwbzzzysczss.jpeg?q=70',
            'https://rukminim2.flixcart.com/image/832/832/xif0q/mobile/h/x/a/-original-imagrxbufb6tqzjc.jpeg?q=70'
        ],
        model:'OPPO A78 ',
        brand:'Oppo',
        price:16770,
        space:'8 GB RAM | 128 GB ROM',
        camera:'50MP + 2MP | 8MP Front Camera',
        battery:'5000 mAh Battery',
        count:1,
        isAdded:false,
        type:'Mobile',   
        isTrending:false
    },
    {
        id:9,
        img:'https://m.media-amazon.com/images/I/61SSVxTSs3L._SX679_.jpg',
        model:'ColorFit Pulse',
        brand:'Noise',
        price:1499,
        color:'black',
        count:1,
        isAdded:false,
        type:'Watch',   
        isTrending:true
    },
    {
        id:10,
        img:'https://m.media-amazon.com/images/I/61Bdfmo2s0L._SX679_.jpg',
        model:'Lumos',
        brand:'Fire-Boltt',
        price:1499,
        color:'	Steel Black',
        count:1,
        isAdded:false,
        type:'Watch',   
        isTrending:false
    },
    {
        id:11,
        img:'https://m.media-amazon.com/images/I/61YVUOHcrqL._SX679_.jpg',
        model:'Ninja Call Pro',
        brand:'Fire-Bolt',
        price:1199,
        color:'Navy Blue',
        count:1,
        isAdded:false,
        type:'Watch',   
        isTrending:false
    },
    {
        id:12,
        img:'https://m.media-amazon.com/images/I/61akt30bJsL._SX679_.jpg',
        model:'Fire-Boltt',
        brand:'Noise',
        price:1299,
        color:'	black',
        count:1,
        isAdded:false,
        type:'Watch',   
        isTrending:true
    },
    {
        id:13,
        img:'https://m.media-amazon.com/images/I/61YTjbpBTTL._SX679_.jpg',
        model:'Wave Style',
        brand:'Boat',
        price:1099,
        color:'	black',
        count:1,
        isAdded:false,
        type:'Watch',   
        isTrending:false
    },
    {
        id:14,
        img:'https://m.media-amazon.com/images/I/61RqU14G4ZL._SX679_.jpg',
        model:'ColorFit Pro',
        brand:'Noise',
        price:1099,
        color:'Red',
        count:1,
        isAdded:false,
        type:'Watch',   
        isTrending:false
    },
    {
        id:15,
        img:'https://m.media-amazon.com/images/I/41RVsZAmNGL._SX300_SY300_QL70_FMwebp_.jpg',
        model:'Ninja Call Pro',
        brand:'Fire-Boltt',
        price:1199,
        color:'white',
        count:1,
        isAdded:false,
        type:'Watch',   
        isTrending:false
    },
    {
        id:16,
        img:'https://m.media-amazon.com/images/I/71OruInXiNL._SX679_.jpg',
        model:'Case X',
        brand:'Fire-Boltt',
        price:5999,
        color:'Red',
        count:1,
        isAdded:false,
        type:'Watch',   
        isTrending:true
    },

    {
        id:17,
        img:'https://m.media-amazon.com/images/I/71z4wWmnvAL._SX679_.jpg',
        model:'ZEB-NBC 4S',
        brand:'Zebronics',
        price:30999,
        color:'Blue',
        space:'16GB | 512GB',
        operating_system:'Windows 11 Home',
        count:1,
        isAdded:false,
        type:'Laptop',   
        isTrending:true
    },
    {
        id:18,
        img:'https://m.media-amazon.com/images/I/713etE3fZTL._SX679_.jpg',
        model:'Vostro 3520',
        brand:'Dell',
        price:36990,
        color:'black',
        space:'8GB | 512GB',
        operating_system:'Windows 11 Home',
        count:1,
        isAdded:false,
        type:'Laptop',   
        isTrending:false
    },
    {
        id:19,
        img:'https://m.media-amazon.com/images/I/71W5FiBP6WL._SX679_.jpg',
        model:'15s-fy5005TU',
        brand:'HP',
        price:43990,
        color:'black',
        space:'8GB | 1TB',
        operating_system:'Windows 11 Home',
        count:1,
        isAdded:false,
        type:'Laptop',   
        isTrending:false
    },
    {
        id:20,
        img:'https://m.media-amazon.com/images/I/71kJlKb2r8L._SX679_.jpg',
        model:'Vivobook 15',
        brand:'Asus',
        price:26990,
        color:'silver',
        space:'8GB | 512GB',
        operating_system:'Windows 11 Home',
        count:1,
        isAdded:false,
        type:'Laptop',   
        isTrending:true
    },
    {
        id:21,
        img:'https://m.media-amazon.com/images/I/51CTXHQux0L._SX679_.jpg',
        model:'Vostro 3510',
        brand:'Dell',
        price:48490,
        color:'Carbon',
        space:'8GB | 512GB',
        operating_system:'Windows 11 Home',
        count:1,
        isAdded:false,
        type:'Laptop',   
        isTrending:false
    },
    {
        id:22,
        img:'https://m.media-amazon.com/images/I/81NFEnJDJ6L._SX679_.jpg',
        model:'Galaxy Book3',
        brand:'Samsung',
        price:64990,
        color:'Silver',
        space:'8GB | 512GB',
        operating_system:'Windows 11 Home',
        count:1,
        isAdded:false,
        type:'Laptop',   
        isTrending:true
    },
    {
        id:23,
        img:'https://m.media-amazon.com/images/I/71TPda7cwUL._SX679_.jpg',
        model:'MacBook Air',
        brand:'Apple',
        price:83990,
        color:'Silver',
        space:'8GB | 256GB',
        operating_system:'Mac OS',
        count:1,
        isAdded:false,
        type:'Laptop',   
        isTrending:false
    },
    {
        id:24,
        img:'https://m.media-amazon.com/images/I/618d5bS2lUL._SX679_.jpg',
        model:'MacBook Pro',
        brand:'Apple',
        price:399900,
        color:'Black',
        space:'48GB | 1TB',
        operating_system:'Mac OS',
        count:1,
        isAdded:false,
        type:'Laptop',   
        isTrending:false
    },

]


const fashionData = [
    {
        id:25,
        img:'https://m.media-amazon.com/images/I/61SRj3IzD1L._SY879_.jpg',
        model:'Denim',
        brand:"Levi's",
        price:699,
        color:'blue',
        count:1,
        isAdded:false,
        type:'Jeans',   
        isTrending:true
    },
    {
        id:26,
        img:'https://m.media-amazon.com/images/I/61KGHTiK5sL._SX679_.jpg',
        model:'Denim',
        brand:"Levi's",
        price:629,
        color:'brown',
        count:1,
        isAdded:false,
        type:'Jeans',   
        isTrending:false
    },
    {
        id:27,
        img:'https://m.media-amazon.com/images/I/61squlDBu2L._SY879_.jpg',
        model:'Slim',
        brand:"Levi's",
        price:1829,
        color:'black',
        count:1,
        isAdded:false,
        type:'Jeans',   
        isTrending:false
    },
    {
        id:28,
        img:'https://m.media-amazon.com/images/I/61KGHTiK5sL._SX679_.jpg',
        model:'Slim',
        brand:"Billford",
        price:629,
        color:'brown',
        count:1,
        isAdded:false,
        type:'Jeans',   
        isTrending:true
    },
    {
        id:29,
        img:'https://m.media-amazon.com/images/I/611JW98mezL._SX679_.jpg',
        model:'Slim',
        brand:"Louis Stich",
        price:2375,
        color:'brown',
        count:1,
        isAdded:false,
        type:'Jeans',   
        isTrending:false
    },
    {
        id:30,
        img:'https://m.media-amazon.com/images/I/81HoA9uLEPL._SY879_.jpg',
        model:'Slim',
        brand:"Ketch",
        price:587,
        color:'LightBlue',
        count:1,
        isAdded:false,
        type:'Jeans',   
        isTrending:true
    },
    {
        id:31,
        img:'https://m.media-amazon.com/images/I/A176kJizsPL._SX679_.jpg',
        model:'Slim',
        brand:"Levi's",
        price:1889,
        color:'brown',
        count:1,
        isAdded:false,
        type:'Jeans',   
        isTrending:false
    },
    {
        id:32,
        img:'https://m.media-amazon.com/images/I/81iqWYMhlnL._SY879_.jpg',
        model:'Zogger',
        brand:"AmazonBrand",
        price:899,
        color:'blue',
        count:1,
        isAdded:false,
        type:'Jeans',   
        isTrending:false
    },
    {
        id:33,
        img:'https://m.media-amazon.com/images/I/61fkTWm-SnL._SY695_.jpg',
        model:"Men's Boot",
        brand:"AnkleShoes",
        price:1549,
        color:'black',
        count:1,
        isAdded:false,
        type:'Shoes',   
        isTrending:false
    },
    {
        id:34,
        img:'https://m.media-amazon.com/images/I/41Dv2ycCHVL.jpg',
        model:"Casual Boot",
        brand:"AnkleShoes",
        price:498,
        color:'whiteandblack',
        count:1,
        isAdded:false,
        type:'Shoes',   
        isTrending:true
    },
    {
        id:35,
        img:'https://m.media-amazon.com/images/I/71JhX1D0+XL._SY695_.jpg',
        model:"Men's Boot",
        brand:"YohoShoes",
        price:1659,
        color:'black',
        count:1,
        isAdded:false,
        type:'Shoes',   
        isTrending:false
    },
    {
        id:36,
        img:'https://m.media-amazon.com/images/I/71JhX1D0+XL._SY695_.jpg',
        model:"Men's Boot",
        brand:"YohoShoes",
        price:1659,
        color:'black',
        count:1,
        isAdded:false,
        type:'Shoes',   
        isTrending:true
    },
    {
        id:37,
        img:'https://m.media-amazon.com/images/I/81TBFpGVlCL._SY695_.jpg',
        model:"Rojas Sneaker",
        brand:"US POLO",
        price:2228,
        color:'Red and white',
        count:1,
        isAdded:false,
        type:'Shoes',   
        isTrending:true
    },
    {
        id:38,
        img:'https://m.media-amazon.com/images/I/51kZRxvxg0L._SY695_.jpg',
        model:"Sneaker",
        brand:"YSCROWS",
        price:422,
        color:'white',
        count:1,
        isAdded:false,
        type:'Shoes',   
        isTrending:false
    },
    {
        id:39,
        img:'https://m.media-amazon.com/images/I/5149FttjJuL._SY695_.jpg',
        model:"Men's Sneaker",
        brand:"Red Tap",
        price:1599,
        color:'white',
        count:1,
        isAdded:false,
        type:'Shoes',   
        isTrending:false
    },
    {
        id:40,
        img:'https://m.media-amazon.com/images/I/41-reQfTyoL.jpg',
        model:"Casual Sneaker",
        brand:"LIPRIXTA",
        price:549,
        color:'brown',
        count:1,
        isAdded:false,
        type:'Shoes',   
        isTrending:false
    },
    {
        id:41,
        img:'https://m.media-amazon.com/images/I/81wFLUDzAbL._SY879_.jpg',
        model:"Tshirt's",
        brand:"AUSK",
        price:239,
        color:'Mahroon',
        count:1,
        isAdded:false,
        type:'Tshirts',   
        isTrending:true
    },
    {
        id:42,
        img:'https://m.media-amazon.com/images/I/71ISzvgAl2L._SY879_.jpg',
        model:"Tshirt's",
        brand:"Polo Shirt",
        price:649,
        color:'blue',
        count:1,
        isAdded:false,
        type:'Tshirts',   
        isTrending:false
    },
    {
        id:43,
        img:'https://m.media-amazon.com/images/I/71eUwDk8z+L._SY879_.jpg',
        model:"Tshirt's",
        brand:"Polo Shirt",
        price:699,
        color:'black',
        count:1,
        isAdded:false,
        type:'Tshirts',   
        isTrending:false
    },
    {
        id:44,
        img:'https://m.media-amazon.com/images/I/61S5nUPVufL._SX679_.jpg',
        model:"Tshirt's",
        brand:"London Hills",
        price:299,
        color:'green',
        count:1,
        isAdded:false,
        type:'Tshirts',   
        isTrending:true
    },
    {
        id:45,
        img:'https://m.media-amazon.com/images/I/517Hfmb19RL._SY879_.jpg',
        model:"Tshirt's",
        brand:"Polo Hills",
        price:380,
        color:'white',
        count:1,
        isAdded:false,
        type:'Tshirts',   
        isTrending:false
    },
    {
        id:46,
        img:'https://m.media-amazon.com/images/I/619uXd9I3iL._SX679_.jpg',
        model:"Tshirt's",
        brand:"BULLMER",
        price:289,
        color:'black',
        count:1,
        isAdded:false,
        type:'Tshirts',   
        isTrending:true
    },
    {
        id:47,
        img:'https://m.media-amazon.com/images/I/61p21cELnEL._SX679_.jpg',
        model:"Tshirt's",
        brand:"London Hills",
        price:299,
        color:'green',
        count:1,
        isAdded:false,
        type:'Tshirts',   
        isTrending:false
    },
    {
        id:48,
        img:'https://m.media-amazon.com/images/I/517Tys7oz-L._SX679_.jpg',
        model:"Tshirt's",
        brand:"EYEBOGLER",
        price:199,
        color:'red',
        count:1,
        isAdded:false,
        type:'Tshirts',   
        isTrending:false
    },
]




export default accessories;
export {fashionData};